create table Customers(
  email character varying(50 char)
    constraint Customers_PK
      primary key
    constraint Customers_CHK_Email
      check (email like '_%@_%._%'),
  first_name character varying(50 char) not null,
  last_name character varying(50 char) not null
);

create table RoomTypes(
  type_name character varying(50 char)
    constraint RoomTypes_PK
      primary key,
  description character varying(255 char),
  price_per_night numeric(10,2) not null
);

create table Rooms(
  room_number numeric(4,0)
    constraint Rooms_PK
      primary key,
  type_name character varying(50 char)
    constraint Rooms_FK_RoomTypes
      references RoomTypes(type_name)
);

create table Reservations(
  reservation_id number generated by default on null as identity
    constraint Reservations_PK
      primary key,
  email character varying(50 char)
    constraint Reservations_FK_Customers
      references Customers(email),
  room_number numeric(4,0)
    constraint Reservations_FK_Rooms
      references Rooms(room_number),
  start_date date not null,
  end_date date not null
);

create table Payments(  
  reservation_id numeric(8,0)
    constraint Payments_PK
      primary key
    constraint Payments_FK_Reservations
      references Reservations(reservation_id),
  amount_paid numeric(10,2) not null,
  payment_date date not null
);

create table Services(
  service_name character varying(50 char)
    constraint Services_PK
      primary key,
  description character varying(255 char),
  price numeric(10,2) not null
);

create table ServicesReservations(
  reservation_id numeric(8, 0)
    constraint ServicesReservations_FK_Reservations
      references Reservations(reservation_id),
  service_name character varying(50 char)
    constraint ServicesReservations_FK_Services
      references Services(service_name),
  constraint ServicesReservations_PK
    primary key(reservation_id, service_name)
);

create table Reviews(
  reservation_id numeric(8,0)
    constraint Reviews_PK
      primary key
    constraint Reviews_FK_Reservations
      references Reservations(reservation_id),
  rating numeric(2,1) 
    constraint Reviews_CHK_Rating
      check (rating between 0 and 5),
  comments character varying(255 char)
);

-- For the Rooms table:
create index idx_rooms_roomtypes on rooms(type_name);
-- For the Reservations table:
create index idx_reservations_customers on reservations(email);
create index idx_reservations_rooms on reservations(room_number);

